### PR TITLE
New nrepl compatibility

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by gfredericks** [comment]
Does this solve all of #7? I don't think it does based on my own experiments, but it'd be useful to know for sure.

What version of leiningen have you tested this with?

I suspect it's worth merging regardless.

**Comment by gfredericks** [comment]
(and also, thank you for the pull request!)

**Comment by anmonteiro** [comment]
@gfredericks it works for me with Lein 2.8.3, but I had to remove the `:dev` profile that loads your https://github.com/gfredericks/nrepl-53-monkeypatch plugin

**Comment by gfredericks** [comment]
I apologize for the delay -- I will be able to wrap this up in a couple weeks.

**Comment by gfredericks** [comment]
This was released as version `0.0.10`.

**Pull request merged**
