### PR TITLE
Syntax fix and some trivial improvements

### PR DESCRIPTION
**Pull request by pangloss**
The `(./break!)` in catch-break! doesn't work with clojure 1.10 so fixed that. While I was looking I added `return!` to enable handling exceptions and continuing, and also added catch-break! to the async namespace.

Handy library! I wish this was included with Cider...

### CODE REVIEW

**Review by gfredericks — APPROVED** [review]
I think the `./break!` thing was always a bug -- a detail from my personal setup (involving [dot-slash-2](https://github.com/gfredericks/dot-slash-2)) that either indicates nobody was using this or they were using it with that same setup.

The rest of this seems fine; I think the `break-return` might have some race conditions involving nested breaks or other things that could be fixed in theory using some mechanism besides a global atom, but I am not motivated to pursue that. I'll probably add a comment.

**Comment by gfredericks** [comment]
Thanks for the contribution!

**Comment by pangloss** [comment]
You're right. `break-return` should be a stack, pushing ::throw when breaking and popping when unbreaking before resuming.

**Comment by gfredericks** [comment]
Released `0.0.12`

**Pull request merged**
